spring.application.name=Air Bnb


##DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=postgres
spring.datasource.password=Akash123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

##will make this common to all the apis
server.servlet.context-path=/api/v1

jwt.secret.key=hbdjhvbhjsnsdbafibisdfdgjknnjghvhsdvcjhbsjhdbjsv