spring.application.name=Air Bnb


##DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=postgres
spring.datasource.password=Akash123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

##will make this common to all the apis
server.servlet.context-path=/api/v1

jwt.secret.key=hbdjhvbhjsnsdbafibisdfdgjknnjghvhsdvcjhbsjhdbjsv

stripe.secret.key=sk_test_51T8HhlSNDX14YrtCkAREewuxnoepeaxsLkyfKrNMJzAu8uuXF7DkytRlFuDraus2mggtaOKMfYqZBv7T1xDXEkY300qdibkboE
frontend.url=http://localhost:8080
stripe.webhook.secret=whsec_e67d5aa065e3922986cb4414cd0a010ee52ab7314e1b29b18eb98087b7e45b6d